version: '2.2'

services:
    phpcron:
        image: roelbindels/php-cron:${DOCKER_PHPCRON_VERSION}
        container_name: ${COMPOSE_PROJECT_NAME}_phpcron
        hostname: ${COMPOSE_PROJECT_NAME}_phpcron
        networks: [stakkr]
        mem_limit: ${DOCKER_PHPCRON_RAM}
        environment:
            FPM_UID: ${DOCKER_UID}
            FPM_GID: ${DOCKER_GID}
            ENVIRONMENT: ${DOCKER_ENVIRONMENT}
        volumes:
            - ${COMPOSE_BASE_DIR}/home/www-data:/home/www-data
            - ${COMPOSE_BASE_DIR}/www:/var/www
            - ${COMPOSE_BASE_DIR}/logs/php:/var/log/php
            - ${COMPOSE_BASE_DIR}/conf/php-fpm-override:/etc/php5/fpm/user-conf.d
            - ${COMPOSE_BASE_DIR}/conf/php-fpm-override:/etc/php/7.0/fpm/user-conf.d
            - ${COMPOSE_BASE_DIR}/conf/php-fpm-override:/etc/php/7.1/fpm/user-conf.d
            - ${COMPOSE_BASE_DIR}/conf/php-fpm-override:/etc/php/7.2/fpm/user-conf.d
            - ${COMPOSE_BASE_DIR}/plugins/phpcron/static/templates/crontab:/etc/cron.d/crontab:ro
        cap_add:
          - NET_ADMIN
          - NET_RAW
